# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b48a64875f4d4dd7f87a5555b1c85e552783d402d30c74b68b61e80375c5f974a5dbc41a4c54ba41693f9dfc2fa1ea317bde31965f622381dd7a5e25d5af5019

test:
  secret_key_base: ae54a1b28dd84dc88bd299b68c1bff2c28f08cecfbc984bd773db12c00dea969b3ffc7cc6428498a6a5c19113c60f624bc542ed530135e2830d25444aed2fb07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
